output_dir: '.'
theme: jekyll-theme-architect
-gems:
 -  - jekyll-mentions
output:
  html_document:
    highlight: textmate
    mathjax: null
    toc_depth: 3
    toc_float:
      collapsed: false
   
   
