output_dir: '.'
output:
  html_document:
    theme: jekyll-theme-architect
    highlight: textmate
    mathjax: null
    toc_depth: 3
    toc_float:
      collapsed: false
   
   -gems:
 -  - jekyll-mentions
