---
title: "Lab06"
author: "Chris Davis"
date: "3/8/2017"
output: 
    html_document:
      df_print: paged
      keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message= F, warning = F, fig.width = 10, fig.height = 10)
```
#Part I
##Load Plot and Shapefile
```{r}
library( maptools )
library( sp )
library(maps)

syr <- readShapePoly( fn="shapefiles/tl_2010_36067_tract10", proj4string=CRS("+proj=longlat +datum=WGS84") )
syr <- syr[as.numeric(as.character(syr$NAME10)) < 64, ]
par( mar=c(0,0,0,0) )
plot( syr,  border="gray10" )

```

##Add Roads
```{r}
roads <- readShapeLines( fn="shapefiles/tl_2015_36_prisecroads", proj4string=CRS("+proj=longlat +datum=WGS84") )

#Extract Intersate
interstate <- roads[ roads$RTTYP == "I" , ]
```
##Look at unclipped portion
```{r}
par( mar=c(0,0,0,0) )
plot( syr,  border="gray80" )
plot( roads, col="steelblue", lwd=2, add=T)
plot(interstate, col = "red", add = T)
```

##Clip
```{r}
library(raster)
library(rgeos)

interstate_clipped <- gIntersection(syr, interstate)


```
##Plot Clipped 
```{r}
plot( syr,  border="gray80" )
#plot( roads_clipped, col="steelblue", lwd=2, add=T)
plot( interstate_clipped, col="red", add=T)
map.scale( metric=F, ratio=F, relwidth = 0.05, cex=0.5 )

```

##Houses
```{r}
library(dplyr)
houses <- read.csv("https://raw.githubusercontent.com/lecy/hedonic-prices/master/Data/Housing%20Price%20In-Class%20Exercise%20(Responses).csv", stringsAsFactors = F)

lat.lon <- read.csv("lat.lon.csv", stringsAsFactors = F)
lat.lon <- lat.lon[ c("lon","lat")]

plot( syr,  border="gray80" )
#plot( roads_clipped, col="steelblue", lwd=2, add=T)
plot( interstate_clipped, col="red", add=T)
map.scale( metric=F, ratio=F, relwidth = 0.05, cex=0.5 )
  
points(lat.lon$lon, lat.lon$lat, pch = 19, cex=.3)
buff <- gBuffer(interstate_clipped, width = .005)
plot(buff, add=T)

```

##Less find the points near dat highway
```{r}

lat.lon <- SpatialPoints(lat.lon, proj4string = CRS("+proj=longlat +datum=WGS84") )

overStuff <- over(lat.lon, buff)
overStuff[is.na(overStuff)] <- 0
nearHighway <- overStuff==1

houses<- mutate(houses, nearHighway)

nearHighway
```

##Less plot it
```{r}
plot(syr, border = "gray80")
plot(interstate_clipped, col = "red", add = T)
points(lat.lon$lon[!nearHighway], lat.lon$lat[!nearHighway], pch = 19, cex = .3)
points(lat.lon$lon[nearHighway], lat.lon$lat[nearHighway], pch = 19, cex = 1, col = "yellow")

```

#Part II
```{r}

library( rgdal )
library( maptools )
library( geojsonio )
library(dplyr)
library(RColorBrewer)
library(maps)

syr <- readOGR(dsn = "shapefiles/syr_parcels.geojson")

industrials <- syr[syr$LandUse=="Industrial", ]
notIndustrials <- syr[syr$LandUse!="Industrial", ]

plot(notIndustrials, col = "grey", border = F)
plot(industrials, add = T, col = "blue", border = F)

```
##Buff it up
```{r}
plot(notIndustrials, col = "grey", border = F)
plot(industrials, add = T, col = "blue", border = F)

industrialBuff <- gBuffer(industrials, width = .003621, capStyle = "FLAT", quadsegs = 1)
plot(industrialBuff, add = T, col = rgb(44, 4, 248, alpha = 50, maxColorValue = 355))
map.scale( metric=F, ratio=F, relwidth = 0.15, cex=0.5 )
```
##Add houses
```{r}
plot(notIndustrials, col = "grey", border = F)
plot(industrials, add = T, col = "blue", border = F)

plot(industrialBuff, add = T, col = rgb(44, 4, 248, alpha = 50, maxColorValue = 355))
map.scale( metric=F, ratio=F, relwidth = 0.15, cex=0.5 )
points(lat.lon$lon, lat.lon$lat, pch = 19, cex=.2)
```

##Let's get some overs
```{r}
lat.lon <- read.csv("lat.lon.csv", stringsAsFactors = F)
lat.lon <- lat.lon[ c("lon","lat")]
lat.lon <- SpatialPoints(lat.lon, proj4string = CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0") )
overs <- over(lat.lon, industrialBuff)
nearIndustry <- overs==1
names(nearIndustry) <- NULL
nearIndustry[is.na(nearIndustry)]<- F
houses <- cbind(houses, nearIndustry)
```
##Let's plot this
```{r}
plot(notIndustrials, col = "grey", border = F)
plot(industrials, add = T, col = "blue", border = F)

points(lat.lon$lon[nearIndustry], lat.lon$lat[nearIndustry], pch = 19, cex=.4, col = "yellow")
points(lat.lon$lon[!nearIndustry], lat.lon$lat[!nearIndustry], pch = 19, cex=.2)
```




##Now with schools
```{r}
schools <- syr[syr$LandUse=="Schools", ]
notSchools <- syr[syr$LandUse!="Schools", ]

plot(notSchools, col = "grey", border = F)
plot(schools, add = T, col = "red", border = F)

```
##Less add the buffer
```{r}
plot(notSchools, col = "grey", border = F)
plot(schools, add = T, col = "red", border = F)

schoolBuff <- gBuffer(schools, width = .001812, capStyle = "FLAT", quadsegs = 1)
plot(schoolBuff, add = T, col = rgb(248, 18, 18, alpha = 50, maxColorValue = 355))
map.scale( metric=F, ratio=F, relwidth = 0.15, cex=0.5 )
```
##Less plot some houses
```{r}
plot(notSchools, col = "grey", border = F)
plot(schools, add = T, col = "red", border = F)

plot(schoolBuff, add = T, col = rgb(248, 18, 18, alpha = 50, maxColorValue = 355))
map.scale( metric=F, ratio=F, relwidth = 0.15, cex=0.5 )
points(lat.lon$lon, lat.lon$lat, pch = 19, cex=.2)

```

##Let's over
```{r}
lat.lon <- read.csv("lat.lon.csv", stringsAsFactors = F)
lat.lon <- lat.lon[ c("lon","lat")]
lat.lon <- SpatialPoints(lat.lon, proj4string = CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0") )
overs <- over(lat.lon, schoolBuff)
nearSchools <- overs==1
names(nearSchools) <- NULL
nearSchools[is.na(nearSchools)]<- F
houses <- cbind(houses, nearSchools)

```

##Less plot it
```{r}
plot(notSchools, col = "grey", border = F)
plot(schools, add = T, col = "red", border = F)

points(lat.lon$lon[nearSchools], lat.lon$lat[nearSchools], pch = 19, cex=.4, col = "yellow")
points(lat.lon$lon[!nearSchools], lat.lon$lat[!nearSchools], pch = 19, cex=.2)
```

